// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package queries

import (
	"context"
)

const empty = `-- name: Empty :exec
SELECT 1
`

func (q *Queries) Empty(ctx context.Context) error {
	_, err := q.db.Exec(ctx, empty)
	return err
}
