// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func App() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html><head><title>Openglide :: Open source paraglide and hangglide sites</title><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><link rel=\"stylesheet\" href=\"https://unpkg.com/leaflet@1.9.4/dist/leaflet.css\"><script src=\"https://unpkg.com/leaflet@1.9.4/dist/leaflet.js\"></script><link href=\"css/styles.css\" rel=\"stylesheet\"><script src=\"js/app.js\" async></script><script src=\"js/hyperscript.js\" async></script><script src=\"js/htmx.js\" async></script></head><body class=\"h-full\"><div id=\"container\" class=\"flex flex-col h-screen\"><div id=\"searchBox\" class=\"bg-white p-2 rounded shadow flex items-center space-x-2\"><div class=\"relative w-96\"><div class=\"flex\"><input type=\"text\" id=\"searchInput\" placeholder=\"Search location or coordinates\" class=\"w-52 px-2 py-1 border border-gray-300 rounded-l-lg focus:outline-none focus:ring focus:border-blue-400\" _=\"on keyup debounced at 750ms showSearchSuggestions()\"> <button id=\"search_button\" class=\"px-3 py-1 rounded-r-lg bg-blue-500 text-white hover:bg-blue-600\" _=\"on click doSearch() then console.log(&#39;did search&#39;)\">Search</button></div><div id=\"searchSuggestions\" class=\"absolute mt-2 left-0 bg-white border border-gray-200 rounded-b shadow z-[10000] max-h-56 w-full overflow-y-auto\" style=\"display:none;\"></div></div></div><div class=\"flex h-screen\"><div id=\"sidebar\" class=\"w-[300px] min-w-[180px] max-w-[40vw] p-2.5 bg-gray-100 border-r border-gray-300 overflow-y-auto\"><h3 class=\"text-lg font-semibold mb-2\">Sites</h3><ul id=\"siteList\" class=\"list-none p-0\"></ul></div><div id=\"map\" class=\"flex-1 relative\"></div></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
